### ISSUE TITLE
 echo=True in "Lazy and Eager Relationships"

### ISSUE THREAD

**Issue by frchalaoux** [miguelgrinberg/retrofun#2]
Hi Miguel,

In chapter 3, in "Lazy and Eager Relationships" echo=True does not produce the log lines in all exercises !

Any idea ?

François-Régis

**Comment by miguelgrinberg** [comment]
Do you mean that you get logs in some, but not all? Or you never get logs? What change did you make to add the `echo` setting?

**Comment by frchalaoux** [comment]
Hi Miguel,
I set the log with:

> engine = create_engine(os.environ['DATABASE_URL'], echo=True)

And it works now. Don't know why. Thank for your answer and congratulation for your book. It answer to so many questions I had in these topics. You're great !
