### ISSUE TITLE
datetime.utcnow is deprecated

### ISSUE THREAD

**Issue by arunksoman** [miguelgrinberg/retrofun#5]
Hi. I am a reader of your book. The datetime.utcnow() function is deprecated. They suggests following way to get utc time.

```python
from datetime import datetime, timezone
utc_time = datetime(timezone.utc)
```

[Here](https://github.com/miguelgrinberg/retrofun/blob/4c71d1555895b4d090519fc200dd03a07a3f7ce3/chapter5/models.py#L122), the problem is we have to pass unexecuted function as default parameter. So what is the preferred method in newer python versions to get current utc time?

**Comment by miguelgrinberg** [comment]
You will need to create a wrapper function that you can pass here. See [my blog post](https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated) for ideas.

**Comment by ddahan** [comment]
I use this: `timestamp: Mapped[datetime] = mapped_column(default=lambda: datetime.now(UTC))`
